#!/usr/bin/env ruby

require 'kafkr'
require 'find'
require 'digest'

PORT = ENV['KAFKR_PORT'] || 4000
$current_consumer = nil
$restart_required = false

# Signal handler for setting a restart flag
Signal.trap('USR1') do
  $restart_required = true
end

def stop_consumer
  if $current_consumer
    puts 'Stopping current consumer...'
    # Add logic to gracefully stop the consumer, e.g., closing connections
    $current_consumer = nil
  end
end

def list_registered_handlers
  Kafkr::Consumer.handlers.each do |handler|
    handler_name = handler.class.name.split('::').last
    handler_name.gsub!(/Handler$/, '') # Remove 'Handler' from the name
    puts "#{handler_name} loaded - ok!"
  end
end

# Method to start the consumer
def start_consumer
  puts "Starting consumer on port #{PORT}!"
  Kafkr::Consumer.configure do |config|
    config.port = PORT
  end

  Kafkr::Consumer.load_handlers
  list_registered_handlers

  $current_consumer = Kafkr::Consumer.new
  $current_consumer.listen do |message|
    # Processing of the message
  end
end

def reload_handlers(file_checksums)
  #puts 'Reloading handlers...'
  Find.find(Kafkr::Consumer::HANDLERS_DIRECTORY) do |path|
    next unless File.file?(path)

    load path
  end
  Kafkr::Consumer.load_handlers
  list_registered_handlers
end

def monitor_handlers(file_checksums)
  #puts 'Monitoring for handler changes...'
  loop do
    changed = false
    Find.find(Kafkr::Consumer::HANDLERS_DIRECTORY) do |path|
      next unless File.file?(path)

      current_checksum = Digest::MD5.file(path).hexdigest
      if file_checksums[path] != current_checksum
        file_checksums[path] = current_checksum
        #puts "Change detected in #{path}"
        changed = true
      end
    end

    reload_handlers(file_checksums) if changed

    sleep 5
  end
end

file_checksums = {}
monitoring_thread = Thread.new { monitor_handlers(file_checksums) }
start_consumer

begin
  loop do
    if $restart_required
      #puts 'Restart signal received. Restarting consumer...'
      stop_consumer
      start_consumer
      $restart_required = false
    end
    sleep 1
  end
rescue LoadError => e
  puts "Failed to load Kafkr: #{e.message}"
  exit(1)
rescue => e
  puts "An error occurred: #{e.message}"
  exit(1)
rescue Interrupt
  puts "\nConsumer shutting down gracefully..."
  stop_consumer
  exit(0)
ensure
  monitoring_thread.kill if monitoring_thread
end
