#!/usr/bin/env ruby
require_relative "../lib/kafkr.rb"

PORT = ENV["KAFKR_PORT"] || 4000

begin
  require "kafkr"
rescue LoadError => e
  Kafkr.log "Failed to load Kafkr: #{e.message}"
  exit(1)
end

begin
  server = Kafkr::Log.new(PORT.to_i)
  Kafkr.log "Kafkr Log version #{Kafkr::VERSION} started on port #{PORT}!"
  server.start
rescue => e
  Kafkr.log "An error occurred: #{e.message}"
  exit(1)
rescue Interrupt
  Kafkr.log "\nLog server shutting down gracefully..."
  server.stop if server.respond_to?(:stop)
  exit(0)
end
