#!/usr/bin/env ruby
PORT = ENV["KAFKR_PORT"] || 4000

begin
  require "kafkr"
rescue LoadError => e
  puts "Failed to load Kafkr: #{e.message}"
  exit(1)
end

begin
  Kafkr::Producer.configure do |config|
    config.host = "localhost"
  end

  while line = Readline.readline("> ", true)
    break if line == "exit"

    if line.include? "<=>"
      puts "sync"
      Kafkr::Producer.send_message(line)
    end
    
    Kafkr::Producer.send_message(line)
  
  end
rescue => e
  puts "An error occurred: #{e.message}"
  exit(1)
rescue Interrupt
  puts "\nProducer server shutting down gracefully..."
  exit(0)
end
